@extends('layouts.front')
@section('title', 'Home')
@section('content')
@include('front.home.sections.hero')
@include('front.home.sections.feature')
@include('front.home.sections.top')
@include('front.home.sections.about')
@include('front.home.sections.category')
@include('front.home.sections.brand')
@include('front.home.sections.testimoni')
@endsection